apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
  namespace: development
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer-container
        image: chrdie/kafka-producer:latest
        env:
        - name: KAFKA_TOPIC
          value: test
        - name: KAFKA_BOOTSTRAP_SERVER
          value: kafka-controller-0.kafka-controller-headless.development.svc.cluster.local:9092
        - name: KAFKA_SECURITY_PROTOCOL
          value: SASL_PLAINTEXT
        - name: KAFKA_SASL_MECHANISM
          value: SCRAM-SHA-512
        - name: KAFKA_USERNAME
          value: user1
        - name: KAFKA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-user-passwords
              key: client-passwords
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
